export const COMPLETE_TASK = "COMPLETE_TASK";
export const RECOVER_TASK = "RECOVER_TASK";
export const CLEAR_CHAT = "CLEAR_CHAT";
export const ENABLE_ALL_SUBSCRIBE_CONTROL = "ENABLE_ALL_SUBSCRIBE_CONTROL";
export const DISABLE_ALL_SUBSCRIBE_CONTROL = "DISABLE_ALL_SUBSCRIBE_CONTROL";
export const CLEAR_CHAT_BOT = "CLEAR_CHAT_BOT";
